version: "3.9"

services:
  gesture-app:
    build: .
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host